//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETCATEGORY
    {
        public int ID { get; set; }
        public string Nam { get; set; }
        public int PositionCategory { get; set; }
        public int CustomerCategory { get; set; }
        public double Price { get; set; }
    }
}
