//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public int ID { get; set; }
        public int PositionAmount { get; set; }
        public string Projector { get; set; }
        public string Audio { get; set; }
        public double Stretch { get; set; }
        public string Status { get; set; }
        public string OtherDevice { get; set; }
    }
}
